package pngparse

import (
	"bytes"
	"image"
	"image/color"
	"image/png"
	"os"
	"path/filepath"
	"testing"
)

// TestFixturesDecodeAndParse verifies the committed synthetic fixtures in
// testdata/: they must parse cleanly with pngparse AND fully decode with the
// standard library image/png decoder, proving they are real, renderable PNGs.
func TestFixturesDecodeAndParse(t *testing.T) {
	indexedPath := filepath.Join("testdata", "1x1-indexed.png")
	rgbPath := filepath.Join("testdata", "2x2-rgb-text.png")
	corruptPath := filepath.Join("testdata", "2x2-rgb-text-corrupt.png")

	for _, path := range []string{indexedPath, rgbPath, corruptPath} {
		if _, err := os.Stat(path); err != nil {
			t.Fatalf("missing fixture %s (run: go run ./cmd/pnggen)", path)
		}
	}

	// --- 1x1 indexed ---
	data := mustRead(t, indexedPath)
	p, err := ParseFile(indexedPath)
	if err != nil {
		t.Fatal(err)
	}
	noProblems(t, p)
	if p.Header.Width != 1 || p.Header.Height != 1 ||
		p.Header.BitDepth != 4 || p.Header.ColorType != 3 {
		t.Errorf("indexed header = %+v", p.Header)
	}
	im := decodePNG(t, data)
	if got := im.Bounds(); got.Dx() != 1 || got.Dy() != 1 {
		t.Fatalf("decoded %dx%d, want 1x1", got.Dx(), got.Dy())
	}
	// Palette entry 0 of the generated ramp is (0,255,0).
	first := color.RGBA{0, 255, 0, 255}
	if c := im.At(0, 0); c != first {
		t.Errorf("pixel = %v, want (0,255,0)", c)
	}

	// --- 2x2 RGB with tEXt + zTXt ---
	data = mustRead(t, rgbPath)
	p, err = ParseFile(rgbPath)
	if err != nil {
		t.Fatal(err)
	}
	noProblems(t, p)
	if p.Header.Width != 2 || p.Header.Height != 2 || p.Header.ColorType != 2 {
		t.Errorf("rgb header = %+v", p.Header)
	}
	texts := map[string]string{}
	for _, e := range p.TextInfo {
		texts[e.Keyword] = e.Text
	}
	if texts["Author"] != "pngparse fixture builder" {
		t.Errorf("tEXt Author = %q", texts["Author"])
	}
	if texts["Comment"] != "generated by cmd/pnggen" {
		t.Errorf("zTXt Comment = %q", texts["Comment"])
	}
	im = decodePNG(t, data)
	want := map[image.Point]color.Color{
		{0, 0}: color.RGBA{255, 0, 0, 255},
		{1, 0}: color.RGBA{0, 255, 0, 255},
		{0, 1}: color.RGBA{0, 0, 255, 255},
		{1, 1}: color.RGBA{255, 255, 0, 255},
	}
	for pt, c := range want {
		if got := im.At(pt.X, pt.Y); got != c {
			t.Errorf("pixel %v = %v, want %v", pt, got, c)
		}
	}

	// --- corrupted copy: parses, but the IDAT CRC is invalid ---
	data = mustRead(t, corruptPath)
	p, err = Parse(data)
	if err != nil {
		t.Fatal(err)
	}
	if !hasProblem(p, "invalid CRC") {
		t.Errorf("corrupt fixture problems = %v", p.Problems)
	}
	for i := range p.Chunks {
		if p.Chunks[i].TypeString() == "IDAT" && p.Chunks[i].CrcValid {
			t.Error("corrupt fixture IDAT should have CrcValid=false")
		}
	}
	if bytes.Equal(mustRead(t, rgbPath), data) {
		t.Error("corrupt fixture must differ from healthy one")
	}
}

func mustRead(t *testing.T, path string) []byte {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return data
}

func decodePNG(t *testing.T, data []byte) image.Image {
	t.Helper()
	im, err := png.Decode(bytes.NewReader(data))
	if err != nil {
		t.Fatal(err)
	}
	return im
}
