// Command pnggen regenerates the synthetic PNG fixtures in testdata/.
// It writes a 1x1 indexed-color PNG, a 2x2 truecolor PNG carrying tEXt and
// zTXt chunks, and a copy of the latter with one IDAT payload byte flipped
// so the CRC no longer matches (used for smoke tests of error reporting).
package main

import (
	"bytes"
	"compress/zlib"
	"encoding/binary"
	"fmt"
	"hash/crc32"
	"image/png"
	"os"
	"path/filepath"
)

var pngSignature = []byte{0x89, 'P', 'N', 'G', '\r', '\n', 0x1a, '\n'}

func chunk(t string, data []byte) []byte {
	typeData := make([]byte, 0, 4+len(data))
	typeData = append(typeData, t...)
	typeData = append(typeData, data...)
	out := make([]byte, 0, 8+len(data)+4)
	var u32 [4]byte
	binary.BigEndian.PutUint32(u32[:], uint32(len(data)))
	out = append(out, u32[:]...)
	out = append(out, typeData...)
	binary.BigEndian.PutUint32(u32[:], crc32.ChecksumIEEE(typeData))
	out = append(out, u32[:]...)
	return out
}

func ihdr(w, h uint32, bit, color byte) []byte {
	d := make([]byte, 13)
	binary.BigEndian.PutUint32(d[0:4], w)
	binary.BigEndian.PutUint32(d[4:8], h)
	d[8], d[9], d[10], d[11], d[12] = bit, color, 0, 0, 0
	return chunk("IHDR", d)
}

func deflate(raw []byte) []byte {
	var buf bytes.Buffer
	zw := zlib.NewWriter(&buf)
	if _, err := zw.Write(raw); err != nil {
		panic(err)
	}
	if err := zw.Close(); err != nil {
		panic(err)
	}
	return buf.Bytes()
}

func plte(entries int) []byte {
	d := make([]byte, entries*3)
	for i := 0; i < entries; i++ {
		d[i*3] = byte((i * 255) / (entries - 1))
		d[i*3+1] = byte(255 - (i*255)/(entries-1))
		d[i*3+2] = byte((i * 127) % 256)
	}
	return chunk("PLTE", d)
}

func buildIndexed() []byte {
	raw := []byte{0x00, 0x00} // filter: none; 4-bit pixel value 0
	img := append([]byte(nil), pngSignature...)
	img = append(img, ihdr(1, 1, 4, 3)...)
	img = append(img, plte(16)...)
	img = append(img, chunk("IDAT", deflate(raw))...)
	img = append(img, chunk("IEND", nil)...)
	return img
}

func buildTextRGB() []byte {
	var raw []byte
	// Two scanlines of 2 pixels each: red|green then blue|yellow.
	rows := [][6]byte{
		{255, 0, 0, 0, 255, 0},
		{0, 0, 255, 255, 255, 0},
	}
	for _, row := range rows {
		raw = append(raw, 0x00) // filter: none
		raw = append(raw, row[:]...)
	}
	img := append([]byte(nil), pngSignature...)
	img = append(img, ihdr(2, 2, 8, 2)...)
	img = append(img, chunk("tEXt", []byte("Author\x00pngparse fixture builder"))...)
	img = append(img, chunk("zTXt", append([]byte("Comment\x00\x00"), deflate([]byte("generated by cmd/pnggen"))...))...)
	img = append(img, chunk("IDAT", deflate(raw))...)
	img = append(img, chunk("IEND", nil)...)
	return img
}

func corruptIDATPayload(img []byte) []byte {
	out := append([]byte(nil), img...)
	idx := bytes.Index(out, []byte("IDAT"))
	if idx < 0 {
		panic("IDAT not found")
	}
	length := int(binary.BigEndian.Uint32(out[idx-4 : idx]))
	payload := idx + 4 + length/2
	out[payload] ^= 0xFF
	return out
}

// idatCRCMatches recomputes the CRC of the first IDAT chunk and reports
// whether it equals the stored value.
func idatCRCMatches(img []byte) bool {
	idx := bytes.Index(img, []byte("IDAT"))
	if idx < 0 {
		return false
	}
	length := int(binary.BigEndian.Uint32(img[idx-4 : idx]))
	typeData := img[idx : idx+4+length]
	stored := binary.BigEndian.Uint32(img[idx+4+length : idx+8+length])
	return crc32.ChecksumIEEE(typeData) == stored
}

func verify(data []byte, wantX, wantY int) {
	cfg, err := png.DecodeConfig(bytes.NewReader(data))
	if err != nil {
		panic("fixture does not decode: " + err.Error())
	}
	if cfg.Width != wantX || cfg.Height != wantY {
		panic(fmt.Sprintf("fixture decodes to %dx%d, want %dx%d", cfg.Width, cfg.Height, wantX, wantY))
	}
	im, err := png.Decode(bytes.NewReader(data))
	if err != nil {
		panic("fixture does not fully decode: " + err.Error())
	}
	if im.Bounds().Dx() != wantX || im.Bounds().Dy() != wantY {
		panic("decoded bounds mismatch")
	}
}

func write(dir string) error {
	indexed := buildIndexed()
	textRGB := buildTextRGB()
	corrupt := corruptIDATPayload(textRGB)

	verify(indexed, 1, 1)
	verify(textRGB, 2, 2)
	if idatCRCMatches(corrupt) {
		panic("corrupt fixture unexpectedly has a valid IDAT CRC")
	}

	if err := os.WriteFile(filepath.Join(dir, "1x1-indexed.png"), indexed, 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(dir, "2x2-rgb-text.png"), textRGB, 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(dir, "2x2-rgb-text-corrupt.png"), corrupt, 0o644); err != nil {
		return err
	}
	return nil
}

func main() {
	out := "testdata"
	if len(os.Args) == 2 {
		out = os.Args[1]
	}
	if err := write(out); err != nil {
		fmt.Fprintln(os.Stderr, "pnggen:", err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s/1x1-indexed.png, 2x2-rgb-text.png, 2x2-rgb-text-corrupt.png\n", out)
}
